#!/usr/bin/env python3
"""Apply insertion outcome labels from metadata_template.csv to trial metadata."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any


OUTCOME_KEYS = ["success", "stopped_early", "bounce_count", "retry_count", "notes"]


def parse_bool(value: str | None) -> bool | None:
    if value is None:
        return None
    text = str(value).strip().lower()
    if text in {"", "nan", "none", "null"}:
        return None
    if text in {"1", "true", "yes", "y", "success", "succeeded", "pass"}:
        return True
    if text in {"0", "false", "no", "n", "fail", "failed"}:
        return False
    raise ValueError(f"Cannot parse bool value: {value!r}")


def parse_count(value: str | None) -> int | None:
    if value is None:
        return None
    text = str(value).strip()
    if text.lower() in {"", "nan", "none", "null"}:
        return None
    return int(float(text))


def load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def row_outcomes(row: dict[str, str]) -> dict[str, Any]:
    outcomes: dict[str, Any] = {}
    success = parse_bool(row.get("success"))
    stopped = parse_bool(row.get("stopped_early"))
    bounce = parse_count(row.get("bounce_count"))
    retry = parse_count(row.get("retry_count"))
    notes = (row.get("notes") or "").strip()
    if success is not None:
        outcomes["success"] = success
        outcomes["task_success"] = success
    if stopped is not None:
        outcomes["stopped_early"] = stopped
        outcomes["early_stop"] = stopped
    if bounce is not None:
        outcomes["bounce_count"] = bounce
        outcomes["bounces"] = bounce
    if retry is not None:
        outcomes["retry_count"] = retry
        outcomes["retries"] = retry
    if notes:
        outcomes["notes"] = notes
    return outcomes


def apply_row(row: dict[str, str], *, dry_run: bool, require_complete: bool) -> dict[str, Any]:
    trial_dir_text = (row.get("trial_dir") or "").strip()
    if not trial_dir_text:
        return {"status": "skipped", "reason": "missing trial_dir", "row": row}
    trial_dir = Path(trial_dir_text).expanduser()
    meta_path = trial_dir / "metadata.json"
    force_path = trial_dir / "force_trace.csv"
    if not trial_dir.exists():
        return {"status": "error", "reason": "trial_dir missing", "trial_dir": str(trial_dir)}
    if not force_path.exists():
        return {"status": "error", "reason": "force_trace.csv missing", "trial_dir": str(trial_dir)}

    outcomes = row_outcomes(row)
    complete = "success" in outcomes and "stopped_early" in outcomes
    if require_complete and not complete:
        return {"status": "error", "reason": "success/stopped_early incomplete", "trial_dir": str(trial_dir)}
    if not outcomes:
        return {"status": "skipped", "reason": "no outcome labels", "trial_dir": str(trial_dir)}

    meta = load_json(meta_path)
    before = {key: meta.get(key) for key in OUTCOME_KEYS if key in meta}
    meta.update(outcomes)
    meta["outcome_metadata_source"] = "metadata_template_csv"
    meta["outcome_metadata_complete"] = bool(complete)
    if not dry_run:
        write_json(meta_path, meta)
    return {
        "status": "updated" if not dry_run else "would_update",
        "trial_dir": str(trial_dir),
        "metadata": str(meta_path),
        "before": before,
        "applied": outcomes,
        "outcome_metadata_complete": bool(complete),
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--metadata_csv", required=True,
                        help="metadata_template.csv generated by eval_insertion_rollouts.py")
    parser.add_argument("--output_json", default=None)
    parser.add_argument("--dry_run", action="store_true")
    parser.add_argument("--require_complete", action="store_true",
                        help="Require success and stopped_early labels for every non-empty row.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    csv_path = Path(args.metadata_csv).expanduser()
    rows = list(csv.DictReader(csv_path.open(newline="", encoding="utf-8")))
    results = [
        apply_row(row, dry_run=bool(args.dry_run), require_complete=bool(args.require_complete))
        for row in rows
    ]
    summary = {
        "metadata_csv": str(csv_path),
        "dry_run": bool(args.dry_run),
        "require_complete": bool(args.require_complete),
        "n_rows": len(rows),
        "updated": sum(1 for r in results if r["status"] == "updated"),
        "would_update": sum(1 for r in results if r["status"] == "would_update"),
        "skipped": sum(1 for r in results if r["status"] == "skipped"),
        "errors": sum(1 for r in results if r["status"] == "error"),
        "results": results,
    }
    out_path = Path(args.output_json).expanduser() if args.output_json else csv_path.with_name("metadata_apply_result.json")
    out_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({
        "output_json": str(out_path),
        "updated": summary["updated"],
        "would_update": summary["would_update"],
        "skipped": summary["skipped"],
        "errors": summary["errors"],
    }, ensure_ascii=False, indent=2))
    if summary["errors"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
